// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaJv0dB4W2m83z2zALDFP4zADRzJNHIs4',
    appId: '1:228334701948:web:53dce56f87136a0155a8f9',
    messagingSenderId: '228334701948',
    projectId: 'yayaa-1211',
    authDomain: 'yayaa-1211.firebaseapp.com',
    storageBucket: 'yayaa-1211.firebasestorage.app',
    measurementId: 'G-EMDDF6ZF8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_2PozxXf8B_qu_ijynE2vRmKdGVnmdvM',
    appId: '1:228334701948:android:4bfb7acdfc3f4e8555a8f9',
    messagingSenderId: '228334701948',
    projectId: 'yayaa-1211',
    storageBucket: 'yayaa-1211.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjQY78ad_tFoWkG02D3ecg0G-dJ9iTs2s',
    appId: '1:228334701948:ios:e885ff7cd85c540155a8f9',
    messagingSenderId: '228334701948',
    projectId: 'yayaa-1211',
    storageBucket: 'yayaa-1211.firebasestorage.app',
    iosBundleId: 'mine.com.yayaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjQY78ad_tFoWkG02D3ecg0G-dJ9iTs2s',
    appId: '1:228334701948:ios:e885ff7cd85c540155a8f9',
    messagingSenderId: '228334701948',
    projectId: 'yayaa-1211',
    storageBucket: 'yayaa-1211.firebasestorage.app',
    iosBundleId: 'mine.com.yayaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaJv0dB4W2m83z2zALDFP4zADRzJNHIs4',
    appId: '1:228334701948:web:e6b2451acb3dd42c55a8f9',
    messagingSenderId: '228334701948',
    projectId: 'yayaa-1211',
    authDomain: 'yayaa-1211.firebaseapp.com',
    storageBucket: 'yayaa-1211.firebasestorage.app',
    measurementId: 'G-JB1SBLVPF4',
  );
}
